In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np



import os
os.chdir('C:/Users/bhupe/Desktop/ML_Challenge_Intuit_Last_Date_5_FEB_2018')


df=pd.read_csv('ship_data.csv')

In [2]:
#	Count	the	number	of	passengers	on	the	ship	based	on	Gender.	
df['Gender'].value_counts()

male      577
female    314
Name: Gender, dtype: int64

In [3]:
#	Count	the	number	of	passengers	on	the	ship	based	on	Class.
df['Class'].value_counts()

3    491
1    216
2    184
Name: Class, dtype: int64

In [4]:
#  Count	the	number	of	passengers	on	the	ship	who	are	children	(Age	less	than	16	years).	4
children=df[df['Age'] < 16]
children['Age'].count()

84

In [20]:
#	Find	the	number	of	children	in	the	various	classes
children['Class'].value_counts()

#plotting the data
#a=[[],[]]

children_1=df[(df['Age'] < 16) & (df['Age'] > 0)]
a=children_1['Class'].value_counts().reset_index()
plt.hist2d(list(a['index']),list(a['Class']))        


(array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]]),
 array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. ]),
 array([ 6. , 11.2, 16.4, 21.6, 26.8, 32. , 37.2, 42.4, 47.6, 52.8, 58. ]),
 <matplotlib.image.AxesImage at 0x200a4125c18>)

In [7]:
#Replace	all	NULL	and	NAN	values	in	the	dataset	programatically.
#finding the columns containing null values
d=[]
c=df.columns
for i in c:
    if df[i].isnull().any()==True:
        d.append(i)
Z = df[(df['Age'].notnull()==True) & (df['Age'] > 0)]
l = Z['Age'].mean()        
df['Age']=df['Age'].fillna(l)
for i in range(len(df)):
    if df['Age'][i] < 0 :
        df['Age'][i]=l;
       





In [8]:
from statistics import mode
c=mode(list(df['Embarked']))
df['Embarked']=df['Embarked'].fillna(c)

In [10]:
#	Find	the	number	of	passengers	who	were	alone	and	who	were	with	family.
#passengers who are alone 	
Alone=df[(df['Siblings Count']==0) & (df['Parents Count']==0) ]
print(len(Alone))

#passengers who are with family
with_family=df[(df['Siblings Count']+df['Parents Count']>0) ]
print(len(with_family)) 


537
354


In [11]:
#	What	percentage	of	passengers	survived	in	each	Class	
Classes=df['Class'].value_counts().reset_index()
for i in Classes['index']:
    Survival=df['Survived'].groupby([df['Class']]).get_group(i)
    n=Survival.value_counts()
    m=(n[1]/len(df))*100
    print ("percentage of passengers survived from class "+str(i)+" is ",m)


percentage of passengers survived from class 3 is  13.35578002244669
percentage of passengers survived from class 1 is  15.26374859708193
percentage of passengers survived from class 2 is  9.764309764309765


In [12]:
#    percentage	of	passengers	who	survived,	based	on	Gender 
Gender=df['Gender'].value_counts().reset_index()
for i in Gender['index']:
    Survival=df['Survived'].groupby([df['Gender']]).get_group(i)
    n=Survival.value_counts()
    m=(n[1]/len(df))*100
    print ("percentage of survival of "+i+" passengers is ",m)

percentage of survival of male passengers is  12.2334455667789
percentage of survival of female passengers is  26.15039281705948


In [16]:
#	Did	having	a	family	member	increased	the	chances	of	survival  
passenger_with_family=with_family['Survived'].value_counts()
percent=(passenger_with_family[1]/len(df))*100

passenger_without_family=Alone['Survived'].value_counts()
percent_1=(passenger_without_family[1]/len(df))*100


if percent > percent_1:
    print("yes,having a family member increased the chances of survival" )
else:
    print("No,having a family member did not increase the chances of survival")


yes,having a family member increased the chances of survival


In [17]:
#Classification model




df['Family']=df['Siblings Count']+df['Parents Count']
#X=df.iloc[:,[1,3,4,7,8,10]]
#y=df.iloc[:,9]

#df['Family']=df['Siblings Count']+df['Parents Count']
X=df.iloc[:,[1,3,4,5,6,7,8]]
y=df.iloc[:,9]


X=pd.get_dummies(X)







# Splitting the dataset into the Training set and Test set
from sklearn.cross_validation import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.1, random_state = 0)

# Feature Scaling
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

# Fitting Random Forest Classification to the Training set
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 20, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, y_train)

# Predicting the Test set results
y_pred = classifier.predict(X_test)

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)

In [18]:
y_pred

array([0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0,
       1, 1], dtype=int64)

In [19]:
cm

array([[46,  5],
       [11, 28]])